export class ImageGenerator {
    constructor(canvasId) {
        this.canvas = document.getElementById(canvasId);
        if (!this.canvas) return;
        this.ctx = this.canvas.getContext('2d');
        this.w = this.canvas.width;
        this.h = this.canvas.height;
    }

    async generate(prompt) {
        // Clear canvas
        this.ctx.fillStyle = '#0f0b1e'; // Match app background
        this.ctx.fillRect(0, 0, this.w, this.h);

        // Draw blueprint grid
        this.ctx.strokeStyle = 'rgba(168, 85, 247, 0.1)';
        this.ctx.lineWidth = 1;
        for (let x = 0; x < this.w; x += 30) {
            this.ctx.beginPath(); this.ctx.moveTo(x, 0); this.ctx.lineTo(x, this.h); this.ctx.stroke();
        }
        for (let y = 0; y < this.h; y += 30) {
            this.ctx.beginPath(); this.ctx.moveTo(0, y); this.ctx.lineTo(this.w, y); this.ctx.stroke();
        }

        // Parse prompt to decide what to draw
        const p = prompt.toLowerCase();

        let nodes = [];
        let connections = [];

        // Always have users/clients
        nodes.push({ x: 100, y: this.h / 2, label: 'Clients / Users', icon: '📱', color: '#ec4899' });

        if (p.includes('microservice') || p.includes('backend')) {
            nodes.push({ x: 300, y: this.h / 2, label: 'API Gateway', icon: '🚪', color: '#a855f7' });
            nodes.push({ x: 550, y: this.h / 2 - 100, label: 'Auth Service', icon: '🔐', color: '#3b82f6' });
            nodes.push({ x: 550, y: this.h / 2 + 100, label: 'Core Service', icon: '⚙️', color: '#3b82f6' });

            connections.push([0, 1], [1, 2], [1, 3]);
        } else {
            nodes.push({ x: 400, y: this.h / 2, label: 'Application Server', icon: '🖥️', color: '#3b82f6' });
            connections.push([0, 1]);
        }

        if (p.includes('database') || p.includes('db') || p.includes('sql')) {
            const dbNode = { x: 800, y: this.h / 2, label: 'Primary DB', icon: '🗄️', color: '#4ade80' };
            nodes.push(dbNode);
            connections.push([nodes.length - 2, nodes.length - 1]); // Connect last service to DB
        }

        if (p.includes('cache') || p.includes('redis')) {
            nodes.push({ x: 550, y: this.h / 2, label: 'Redis Cache', icon: '⚡', color: '#f59e0b' });
            connections.push([1, nodes.length - 1]);
        }

        if (p.includes('queue') || p.includes('kafka') || p.includes('pub-sub')) {
            nodes.push({ x: 700, y: this.h / 2 + 150, label: 'Message Queue', icon: '📨', color: '#f43f5e' });
            connections.push([nodes.length - 3, nodes.length - 1]);
        }

        // Draw connections with glowing lines
        this.ctx.lineWidth = 2;
        this.ctx.shadowBlur = 10;
        this.ctx.shadowColor = 'rgba(168, 85, 247, 0.5)';

        connections.forEach(([i, j]) => {
            const n1 = nodes[i];
            const n2 = nodes[j];

            this.ctx.beginPath();
            this.ctx.strokeStyle = n1.color;
            this.ctx.setLineDash([5, 5]);
            this.ctx.moveTo(n1.x, n1.y);

            // Draw curved line
            this.ctx.bezierCurveTo(
                n1.x + 100, n1.y,
                n2.x - 100, n2.y,
                n2.x, n2.y
            );
            this.ctx.stroke();
        });

        // Reset shadow for nodes
        this.ctx.setLineDash([]);

        // Draw nodes
        nodes.forEach(n => {
            // Draw glow
            this.ctx.shadowBlur = 15;
            this.ctx.shadowColor = n.color;

            // Draw box
            this.ctx.fillStyle = 'rgba(20, 14, 40, 0.9)';
            this.ctx.strokeStyle = n.color;
            this.ctx.lineWidth = 2;

            // Helper function to draw rounded rectangle
            this.drawRoundRect(n.x - 60, n.y - 40, 120, 80, 8);
            this.ctx.fill();
            this.ctx.stroke();

            // Turn off shadow for text
            this.ctx.shadowBlur = 0;

            // Draw Icon
            this.ctx.font = '24px Arial';
            this.ctx.textAlign = 'center';
            this.ctx.textBaseline = 'middle';
            this.ctx.fillStyle = '#ffffff';
            this.ctx.fillText(n.icon, n.x, n.y - 10);

            // Draw Text
            this.ctx.font = '12px Inter, sans-serif';
            this.ctx.fillStyle = 'rgba(255, 255, 255, 0.8)';
            this.ctx.fillText(n.label, n.x, n.y + 20);
        });

        // Add "Generated by Nano Banana" watermark
        this.ctx.font = 'bold 14px Inter';
        this.ctx.fillStyle = 'rgba(245, 158, 11, 0.5)'; // Orange
        this.ctx.textAlign = 'right';
        this.ctx.fillText('🍌 Generated by Nano Banana', this.w - 20, this.h - 20);
    }

    drawRoundRect(x, y, width, height, radius) {
        this.ctx.beginPath();
        this.ctx.moveTo(x + radius, y);
        this.ctx.lineTo(x + width - radius, y);
        this.ctx.quadraticCurveTo(x + width, y, x + width, y + radius);
        this.ctx.lineTo(x + width, y + height - radius);
        this.ctx.quadraticCurveTo(x + width, y + height, x + width - radius, y + height);
        this.ctx.lineTo(x + radius, y + height);
        this.ctx.quadraticCurveTo(x, y + height, x, y + height - radius);
        this.ctx.lineTo(x, y + radius);
        this.ctx.quadraticCurveTo(x, y, x + radius, y);
        this.ctx.closePath();
    }
}
